GET http://127.0.0.1:8080/
Content-Type:application/json

##########
POST http://127.0.0.1:8080/
Content-Type:application/json

{
    "name": "wasiq",
    "email": "wasiq.devil@gmail.com",
    "Message":"I have a query"
}